src/components/MatchedText/MatchedText.js
src/components/MatchedText/example.js
src/components/MatchedText/index.js
src/components/index.js
src/styles/_components.scss
src/styles/_constants.scss

- Designed initially for use with flux-ui service filtering

Adds a MatchedText component!

---

src/components/ListItem/ListItem.js
src/components/ListItem/example.js
src/components/ListItem/index.js
src/components/index.js
src/styles/_components.scss

Adds a ListItem component for putting things in lists

---

docs/css/demo.scss
docs/js/App.js
docs/js/ComponentsPage.js
docs/js/LandingPage.js
docs/js/StyleGuidePage.js
src/components/Grid/Grid.js
src/components/Grid/GridRow.js
src/components/Grid/example.js
src/components/Grid/index.js
src/components/index.js
src/styles/_grid.scss

Fixes #14 
Adds a `<GridRow />` component

Add GridRow and styling

---

src/components/Button/Button.js
src/components/Button/example.js
src/styles/_components.scss
src/styles/_constants.scss
styleguide/colors.md

Added primary prop to button

---

src/components/Grid/example.js
src/styles/_grid.scss
src/styles/_mixins.scss

Adds an example requested in #22 and some nicer CSS for the Grid. Also removes margin styling to fix #25

Add grid wrapping example

---

package.json

Relax Redux peer dependencies

---

package.json
src/components/Button/Button.js
src/components/Button/example.js
src/styles/_components.scss
src/styles/_mixins.scss

Adds a `selected` prop to the Button component and a mixin to show a border around selected components.

Add selectable button

---

src/components/Button/Button.js
src/components/Button/example.js
src/styles/_components.scss

Adds a `danger` prop that will turn the button white/red.

Add danger prop to Button

---

src/components/Button/Button.js

Adds a button type prop for doing form stuff.

Add button type

---

src/components/Button/__snapshots__/Button.test.js.snap
src/components/Text/Text.js
src/components/Text/__snapshots__/Text.test.js.snap
src/theme/weave.js

Weave Cloud uses 14px (0.875em). 1em was 16px.

Change text size to 14px for consistency

---

src/theme/weave.js

Adds a 'disabled' status color, per GARG

Add disabled status color

---

README.md
package.json
src/components/Alert/Alert.test.js
src/components/Menu/Menu.test.js
test-setup.js
test-shim.js
yarn.lock

Part of https://github.com/weaveworks/service-ui/issues/1210

Upgrade to React 16

---

src/styles/_constants.scss

This, together with the pull request in [service-ui](https://github.com/weaveworks/service-ui/pull/1666) addresses the issues in #93

Shifting lightgray shade to match service-ui's theme color

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_LiveModeToggle.js

Resolves #71 by replacing the text with icons in Time Travel live mode toggler.

Change Time Travel live mode toggle to icons

---

package.json
yarn.lock

Bump marked dep to v0.3.9

---

package.json
yarn.lock

See https://github.com/weaveworks/service-ui/pull/1728

Update `markdown` to 0.3.12 to fix regression

---

src/components/ListItem/ListItem.js
src/components/ListItem/example.js
src/styles/_components.scss

We have this in use in at least one place (as a leftover from the `material-ui/List` days)

Implement `leftIcon` property for `ListItem`

---

src/components/Dropdown/Dropdown.js

Fixes #118 
Only this line was actually changed. The rest are `prettify` automated changes. https://github.com/weaveworks/ui-components/compare/118-fix-dropdown?expand=1#diff-dae838509391e35fda596d1211449cdbR137

Fix undefined error in Dropdown

---

src/styles/_components.scss

Fixes https://github.com/weaveworks/service-ui/issues/1760

Make list-item content width 100%

---

src/components/CircularProgress/CircularProgress.js
src/components/CircularProgress/example.js
src/components/TimeTravel/example.js
src/utils/example.js

- Add `inline` property
- Add `center` property

Allow inlining and centering of CircularProgress

---

src/components/TimeTravel/TimeTravel.js

Auto-zoom timeline into the initial range

---

src/components/Input/Input.js

Allow for a `textarea` to be optionally used on the `<Input />` component.

Add textarea prop to Input

---

src/components/CircularProgress/CircularProgress.js
src/styles/_components.scss

Resolves https://github.com/weaveworks/service-ui/issues/1353.
Also, consequentialy fixes #115 and helps with https://github.com/weaveworks/service-ui/issues/1838.

Use DotSpinner in CircularProgress

---

src/components/Alert/Alert.js
src/components/Alert/__snapshots__/Alert.test.js.snap

This renders anchors in the same color as text but underlines them.

Improve anchors in alerts

---

src/components/PrometheusGraph/_Legend.js

(cmd-click).
Fixes https://github.com/weaveworks/service-ui/issues/1996

Adds support for selecting multiple PromLegend entries under osx

---

src/components/PrometheusGraph/PrometheusGraph.js

`getSeriesName` prop now defaults to the following set of naming policies (in that order):
* If series has no metrics, name it as query string
* If series has **only one** metric, name it as the value of that metric
* If series has `__name__` key, throw the name in front and stringify the rest as JSON
* Otherwise simply stringify the whole metrics JSON
The only visible change is the second point (see the legend in the screenshot below), which fixes https://github.com/weaveworks/service-ui/issues/1886 (@rade can be the judge if enough to close that issue) and makes some preparatory work for https://github.com/weaveworks/service-ui/pull/2047.

Smarter default PrometheusGraph series naming

---

package.json
yarn.lock

Bump moment.js to v2.21.0

---

.gitignore
src/theme/weave.js
styleguide/Colors.js

Show newly added theme colors on the samples page

---

.prettierrc
package.json
styleguide/Colors.js

- Also adds a little color tester thing.
- Adds weave's .prettierrc

Sort colors on stylesheet by HSL.

---

src/components/PrometheusGraph/PrometheusGraph.js
src/theme/weave.js
styleguide/Colors.js

Move PrometheusGraph color themes to weave theme

---

src/theme/weave.js

Resolves the `ui-components` part of #164.

Collapse yellow theme colors

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/TimeTravel/_RangeSelector.js

Fixes two bugs introduced in #185.
* Time Travel range selector
* Prometheus Graph time scale

Fix parentheses bugs

---

src/theme/weave.js

Collect z-index values semantically

---

src/components/Button/Button.js
src/components/Button/__snapshots__/Button.test.js.snap

No longer have buttons all uppercase

---

.stylelintrc
package.json
src/components/Dialog/Dialog.js
src/components/Dropdown/Dropdown.js
src/components/PrometheusGraph/_Tooltip.js
src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_RangeSelector.js
yarn.lock

The `ui-components` part of #162.

Use z-index values from the theme

---

.babelrc
package.json
yarn.lock

This should help improve the bundle sizes in other projects!

Add lodash helper to improve imports

---

docs/js/ComponentsPage.js

Fix lodash chaining warning

---

.stylelintrc
docs/js/Example.js
src/components/Button/Button.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Input/Input.js
src/components/ListItem/ListItem.js
src/components/PrometheusGraph/_AxesGrid.js
src/components/PrometheusGraph/_DeploymentAnnotations.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Legend.js
src/components/PrometheusGraph/_Tooltip.js
src/components/Text/Text.js
src/components/Text/Text.test.js
src/components/Text/__snapshots__/Text.test.js.snap
src/components/Text/example.js
src/components/TimeTravel/_LiveModeToggle.js
src/components/TimeTravel/_RangeSelector.js
src/components/TimeTravel/_TimelineLabel.js
src/components/TimeTravel/_TimelinePanButton.js
src/components/TimeTravel/_TimestampInput.js
src/theme/weave.js
src/utils/example.js
styleguide/Colors.js
styleguide/Fonts.js
styleguide/Intro.js

Add all theme font sizes

---

src/theme/weave.js

Make notifications sit on top of alerts.

Move notifications on top of alerts in theme z-index

---

.stylelintrc
src/components/Alert/Alert.js
src/components/CircularProgress/CircularProgress.js
src/components/Dropdown/Dropdown.js
src/components/Input/Input.js
src/components/LogoProgress/LogoProgress.js
src/components/PrometheusGraph/_ErrorOverlay.js
src/components/PrometheusGraph/_FocusPoint.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Legend.js
src/components/PrometheusGraph/_Tooltip.js
src/components/TimeTravel/TimeTravel.js
src/theme/weave.js
styleguide/Borders.js

Use theme border radii

---

src/components/TimestampTag/TimestampTag.js
src/components/TimestampTag/example.js
src/components/TimestampTag/index.js
src/components/index.js

Add a component for https://github.com/weaveworks/service-ui/issues/2538.

Add TimestampTag component

---

package.json
src/components/TimeTravel/_TimestampInput.js
yarn.lock

Fixes https://github.com/weaveworks/service-ui/issues/2570.

Autosizes TimestampInput

---

src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/_TimelineDeployments.js
src/components/TimeTravel/_TimelineLabel.js
src/components/TimeTravel/_TimelinePeriodLabels.js
src/components/TimeTravel/_TimelineRange.js

Resolves #179.
Nothing about the behaviour should have changed, only the underlying DOM tree elements.

Move away from SVG rendering in Time Travel timeline

---

src/components/TimeTravel/_TimelineLoader.js

Flip timeline loading animation

---

src/components/Alert/Alert.js
src/components/Alert/Alert.test.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Alert/example.js

Icon will only be shown if a title is also provided
fix #52

add icon, title props to Alert

---

src/components/Alert/Alert.js
src/components/Alert/__snapshots__/Alert.test.js.snap

Resolves issue where alerts no longer showing by default introduced in 67782ba378068e6b01329931797fcc1c0fc3341f

Pass all props through to styled component

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/example.js

Hide deployments info when no data in PrometheusGraph

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js

Resolves #168.
Finally brings seemless re-mounting of `<TimeTravel />` component before. Mostly fixed by assuming the `3000px` timeline width until the real one is discovered.
Two small downsides:
* The left part of the timeline still flickers a bit when switching between pages (because we  stilluse a heuristic width initially):
* Instead of resizing the selected range to one third of the total timeline width, we fix it at `200px` now instead, so that it doesn't depend on the real timeline width which we still get with a delay.

Smoother Time Travel mounting

---

package.json
yarn.lock

allows snapshotting of enzyme mounted components

add enzyme-to-json

---

src/components/Button/Button.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/DataTable/_Header.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap
src/components/Dropdown/Dropdown.js
src/components/LogoProgress/LogoProgress.js
src/components/MatchedText/MatchedText.js
src/components/TimeTravel/_RangeSelector.js
src/components/TimeTravel/_Timeline.js
src/components/_DeploymentAnnotation/DeploymentAnnotation.js
src/theme/atoms.js
src/theme/colors.js
styleguide/Colors.js

UI part of #265.
Settled on the following **accent colors**:

Gather all theme accent colors

---

src/components/Button/Button.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Button/example.js

Pass any props down to html button

---

docs/js/Example.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Dropdown/Dropdown.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Input/Input.js
src/components/ListItem/ListItem.js
src/components/Menu/MenuItem.js
src/components/PrometheusGraph/_AxesGrid.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/TabSelect/_TabButton.js
src/components/TabSelect/__snapshots__/TabSelect.test.js.snap
src/components/Text/__snapshots__/Text.test.js.snap
src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_LiveModeToggle.js
src/components/TimeTravel/_RangeSelector.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/_TimelineLabel.js
src/components/TimestampTag/TimestampTag.js
src/components/_TimestampTooltip/TimestampTooltip.js
src/theme/atoms.js
src/theme/colors.js
src/utils/example.js
styleguide/Colors.js

Collect and rename gray colors

---

src/components/Code/Code.js
src/components/Code/__snapshots__/Code.test.js.snap

show scrollbar outside of code wrapper if overflow

---

src/components/ResourceDial/ResourceDial.js
src/components/ResourceDial/example.js
src/components/ResourceDial/index.js
src/components/index.js

Add Resource Dial component

---

src/components/Code/Code.js
src/components/Code/__snapshots__/Code.test.js.snap

animate copy text to check icon Code component

---

package.json
src/components/Dropdown/Dropdown.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Input/Input.js
src/components/Search/Search.js
src/components/Search/Search.test.js
src/components/Search/_SearchTerm.js
src/components/Search/__snapshots__/Search.test.js.snap
src/components/Search/example.js
src/components/Search/index.js
src/components/index.js
yarn.lock

Closes #192 
Adds a Search component that mimics the one used in scope:
https://drive.google.com/file/d/18inPIxPK40f9bE6t2pAoA1tRxi4sRh4v/view
@fbarl PTAL at the code. @bia Looking for feedback on the design and interaction!

Add Search component

---

src/components/ResourceDial/ResourceDial.js

animation wouldnt happen if props used directly so set them in state

arc animations when mounting/unmounting

---

src/components/Code/example.js
src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Legend.js
src/components/PrometheusGraph/example.js

give context in legend when using an aggreggator.
fixes https://github.com/weaveworks/service-ui/issues/2051

show inital query for aggregate legend

---

src/components/GraphEdge/GraphEdge.js
src/components/GraphEdge/example.js
src/components/GraphEdge/index.js
src/components/GraphNode/shapes/_BaseShape.js
src/components/index.js
src/utils/dom.js

Add GraphEdge component

---

src/components/GraphNode/GraphNode.js

Fix GraphNode labels scaling in Safari

---

src/components/GraphNode/GraphNode.js

Fix GraphNodes labels being always matched

---

src/components/GraphNode/GraphNode.js

Fix GraphNode labels hover area

---

src/components/Dialog/Dialog.js
src/components/Dialog/example.js

Prerequisite for https://github.com/weaveworks/service-ui/pull/2918.

Don't render actions block in Dialog if no actions are passed

---

src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Button/Button.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Dialog/Dialog.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Input/__snapshots__/Input.test.js.snap
src/components/MatchedText/MatchedText.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Legend.js
src/components/Search/__snapshots__/Search.test.js.snap
src/components/TabSelect/__snapshots__/TabSelect.test.js.snap
src/components/TimeTravel/_Timeline.js
src/theme/borders.js

Reduce soft border radius

---

src/components/DataTable/DataTable.js
src/components/DataTable/DataTable.test.js
src/components/DataTable/_Header.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap

Adds some extra functionality around sorting and fixes incorrect carets.

Data table improvements

---

src/components/Dropdown/Dropdown.js
src/components/Search/Search.js
src/components/Search/__snapshots__/Search.test.js.snap

Fixes some issues with the search component: Passes the label to the `onChange` handler and runs `onChange` `onPin`

Pass label to Search onChange handler and run onChange onPin

---

src/components/GraphNode/GraphNode.js
src/components/GraphNode/example.js

Add position and animation props to GraphNode component

---

src/components/GraphEdge/GraphEdge.js
src/components/GraphNode/GraphNode.js
src/components/GraphNode/_GraphNodeStatic.js
src/components/GraphNode/example.js

Optimization prerequisites for using these in Scope - https://github.com/weaveworks/scope/pull/3262.

Optimize render cycles of GraphNode and GraphEdge components

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Search/__snapshots__/Search.test.js.snap

this commit makes the dropdown the described height of 36px
aligning it with other inputs and aligning it with the original intended
height.

make dropdown actually 36px tall

---

src/components/DataTable/DataTable.js
src/components/DataTable/_Header.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap

DataTable enhancements

---

package.json
yarn.lock

Bump lodash dependendency

---

src/components/GraphEdge/GraphEdge.js
src/components/GraphNode/GraphNode.js

Needed for https://github.com/weaveworks/scope/pull/3262.

Add DOM ref to GraphNode and GraphEdge components

---

.eslintrc
package.json
src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_DeploymentAnnotations.js
src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/_TimelineDeployments.js
src/components/_DeploymentAnnotation/DeploymentAnnotation.js

Support linkable deployment annotations

---

src/components/Search/Search.js
src/components/Search/__snapshots__/Search.test.js.snap
src/components/Search/example.js

Items in search dropdown menu should expand in width to fit content.

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_DeploymentAnnotations.js
src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/_TimelineDeployments.js
src/components/_DeploymentAnnotation/DeploymentAnnotation.js

Add onDeploymentClick hooks to PrometheusGraph and TimeTravel

---

src/components/GraphNode/example.js
src/components/Search/Search.js
src/components/Search/Search.test.js
src/components/Search/example.js

Make Search component fully controlled

---

src/components/Search/Search.js
src/components/Search/Search.test.js
src/components/Search/example.js

- E.g. to be able to clear the input and replace the contents of the search box w/ the filter. ala github

Adds onFilterSelect handler to allow more flexibility in filter combination.

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_Legend.js

Prerequisite for https://github.com/weaveworks/service-ui/issues/3071.

Rendering extra content in PrometheusGraph legend items

---

src/components/Search/Search.js
src/components/Search/_SearchTerm.js
src/components/Search/__snapshots__/Search.test.js.snap

Small UI fixes to Search component

---

src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/GraphNode/GraphNode.js
src/components/Input/__snapshots__/Input.test.js.snap
src/theme/atoms.js
src/theme/colors.js
styleguide/Colors.js

Resolves #148 and #178 - see https://github.com/weaveworks/ui-components/issues/148#issuecomment-413875368
~Should I be changing the version here too?~

Merge success and warning status colors with accent colors

---

src/components/MatchedText/MatchedText.js
src/components/MatchedText/example.js

Never show border on MatchedText

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Input/Input.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/Search/Search.js
src/components/Search/_SearchTerm.js
src/components/Search/__snapshots__/Search.test.js.snap
src/components/Search/example.js

Prerequisite for https://github.com/weaveworks/scope/pull/3337.
* ~Don't propagate (some) key press actions~

Tweaks to Search component

---

src/components/Dialog/Dialog.js
src/components/Dialog/Dialog.test.js

call onClose when pressing escape with Dialog

---

src/components/Search/Search.js
src/components/Search/Search.test.js

Don't pin search terms on blur

---

src/components/ResourceDial/ResourceDial.js

Prerequisite for https://github.com/weaveworks/service-ui/pull/3200.

Added onClick callback to ResourceDial

---

package.json
src/components/Input/Input.test.js
yarn.lock

no need to pass message now just to satisfy issue in upstream lib
jest-styled-components
upstream issue: https://github.com/styled-components/jest-styled-components/issues/189

bug fixed upstream removes need for message

---

src/components/TimeTravel/_RangeSelector.js

Addresses https://github.com/weaveworks/service-ui/issues/3301.
Also partly addresses https://github.com/weaveworks/service-ui/issues/1679.

Adds a weekly time range to TimeTravel

---

src/components/Alert/Alert.js
src/theme/atoms.js

Fixes [#356](https://github.com/weaveworks/ui-components/issues/356)

Fixed styling for Alert component

---

src/components/Alert/Alert.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Alert/example.js
src/components/Input/__snapshots__/Input.test.js.snap
src/theme/atoms.js

See [ui-components/pull/#390comment](https://github.com/weaveworks/ui-components/pull/390#pullrequestreview-167414511).
Removing default alert style and changing unspecified styles to info.

Removing default alert style

---

.circleci/config.yml

Pre-requisite for latest greenkeeper updates

stick to major 8 but allow minor/patch updates

---

README.md

Resolves #411 by doing having a better explanation on how to use the components.

Updated README with styled theme usage instruction

---

package.json

Bump React peerDependencies to >= 16.3.0

---

src/theme/selectors.js

Add a simple example usage for documentation purposes

docs: add example usage to selectors file

---

package.json
src/components/Dropdown/Dropdown.js
src/components/Dropdown/Dropdown.test.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/GraphNode/_GraphNodeStatic.js
src/components/PrometheusGraph/_AxesGrid.js
src/components/Search/__snapshots__/Search.test.js.snap
src/components/Search/example.js
src/components/TimeTravel/_Timeline.js
src/components/_DeploymentAnnotation/DeploymentAnnotation.js
styleguide/Colors.js
yarn.lock

chore: styled-components@3.4.10

---

package.json
src/components/Code/example.js
src/components/DataTable/DataTable.js
src/components/DataTable/_Header.js
src/components/Dropdown/Dropdown.js
src/components/PrometheusGraph/_Chart.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/Search/Search.js
src/components/Search/example.js
styleguide/Layers.js
yarn.lock

- upgrades prettier
- prettify all files w/ new prettier 1.15

Upgrade prettier to 1.15

---

README.md

docs: add info about commit message spec to README

---

src/theme/spacings.js

Resolves #433 
From [424#issuecomment](https://github.com/weaveworks/ui-components/issues/424#issuecomment-442261162)

Proportionally define spacing

---

src/components/PrometheusGraph/_AxesGrid.js

Account for minValue for Y-axis ticks step

---

styleguide/Spacings.js

feat: add spacing showcase

---

styleguide/Borders.js
styleguide/Colors.js
styleguide/Fonts.js
styleguide/Layers.js

Continuing suggestions from #452, I've applied those changes and the new spacing to the rest of our style guide.

fix: standardise spacing and clean up style guide

---

docs/js/Example.js
src/components/Dialog/Dialog.js
src/components/Dropdown/Dropdown.js
src/components/Dropdown/example.js

- Inspired by https://react-select.com/components
Fixes #398

feat: allow over-riding internal dropdown components

---

src/components/Text/Text.js
src/components/Text/example.js
src/theme/fonts.js

Not all of the available sizes were being displayed on the `Text` component tab.

fix: update display of font sizes

---

src/components/ListItem/ListItem.js

fix(listitem): child links of listitem work again

---

src/components/GraphNode/_GraphNodeStatic.js
src/components/GraphNode/shapes/_ShapeDottedTriangle.js

Signed-off-by: Akash Srivastava <akashsrivastava4927@gmail.com>

feat(shape): add dotted triangle shape

---

README.md

Looks a bit better and gets updated automatically!

chore(docs): show badges for peer dependencies in README

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/example.js

feat(dropdown): adds disabled state to dropdown items

---

src/components/Dropdown/Dropdown.js

fix: tweaks dropdown-item disabled style

---

src/components/Dialog/Dialog.js

Dialog title bigger

---

src/components/Dropdown/Dropdown.js

style: dropdown and input have same style when disabled

---

yarn.lock

chore(package): update kind-of to 6.0.3

---

package.json
yarn.lock

Signed-off-by: Daniel Holbach <daniel@weave.works>

chore: update prop-types, react-router, commitlint, webpack-cli
