weaveworks/ui-components

README.md
resolvers.js
resolvers/localModuleProxy.js
resolvers/localModuleProxy.test.js
src/components/index.test.js

Implements #4.
The README contains instructions on how to implement in a test project.
* The resolver module is written in a very generic way, so it could be used for other stuff.
* Hot reloading should work. If you save a file the `ui-components` dir, webpack in the project consuming the lib should do a reload as if its in the same directory.

Add a way to proxy module imports to a local repo

---

package.json
src/components/Button/Button.js
src/components/CircularProgress/CircularProgress.js
src/components/Dialog/Dialog.js
src/components/Grid/GridColumn.js
src/components/Grid/GridRow.js
src/components/ListItem/ListItem.js
src/components/MatchedText/MatchedText.js
src/components/Menu/MenuItem.js
src/components/WeaveCloudLogo/WeaveCloudLogo.js

Since this repo is now used by Scope, we also have to transition to `prop-types` library here to get rid of deprecation errors in Scope: https://github.com/weaveworks/scope/issues/2496

Switch to prop-types library

---

src/components/Dialog/Dialog.js

Only try to render actions if they exist. This makes the Dialog more flexible, as it can be used for any type of modal.

[Dialog] Only map actions if they exist

---

.babelrc
docs/js/App.js
package.json
src/components/Button/Button.js
src/components/Button/Button.test.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Dialog/Dialog.js
src/components/Dialog/Dialog.test.js
src/components/Menu/Menu.test.js
src/components/index.test.js
src/styles/_components.scss
src/theme/weave.js
styleguide/intro.md
theme.js
yarn.lock

Proposal to use styled-components instead of global sass.
Advantages: no global css (less chance of conflict, no need to use something like BEM), use less nested styles, components are now independent "modules", easier to test styling with snapshots
Disadvantages: CSS in JS is still a hot debate. Lots of discussion around this.
---
- `Button` works identically with all of the styles now contained within the component. (Although ThemeProvider is required).
- A theme file is used to define colours, font sizes etc and component specific configuration.
- `.attrs()` is used for `StyledButton` to create a prop called `nature` which is used to lookup button specific configuration in a neat way.
- Stateless components are used.
The future:
- All components would have independent styles, however …

Use styled-components for button

---

package.json

Fixes an issue where utils was not exported by the compiled package. Also uses `yarn` to run tasks in most places. The exception being `npm run version` because `yarn version` is interactive and doesn't detect the next version automagically like `npm`.

Add utils compilation step; convert to yarn task runner

---

.eslintrc
docs/css/demo.scss
src/components/Alert/Alert.js
src/components/Alert/Alert.test.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Alert/example.js
src/components/Alert/index.js
src/components/Button/Button.js
src/components/Button/Button.test.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/index.js
src/theme/weave.js
src/utils/index.js

Adds an Alert component:
Also fixes some issues with `<Button />`:
- Button was ignoring the `style` prop that is used in a couple places in Weave Cloud
- Button would throw an error on click if no callback is provided. This props is optional.

Alert component

---

src/theme/weave.js

It was too close to white before. Also makes gray darker to get a bigger difference between the two.
Before:
After:

Make lightgray darker

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/example.js
src/constants/timeline.js
src/utils/time.js
src/utils/timeline.js

Add support to _beginning of time_, i.e. the earliest timestamp we can jump to in Time Travel as required by https://github.com/weaveworks/scope/issues/2887.
* The new `earliestTimestamp` fields defaults to beginning of year 2014 if no value is provided.
* `onChange` callback has been renamed to `onChangeTimestamp`, so that needs to be updated in Scope when bumping the dep to `ui-components`.

Add earliest timestamp to time travel

---

src/components/LogoProgress/LogoProgress.js

`size` has always been `undefined`.
Backwards compatibility: all _our_ uses have either put this into a wrapper of `width: 150px` or then assigned `display: inline-block`. This PR won't change the rendering of these cases.

Fix default value of LogoProgress `size` property

---

src/components/TimeTravel/RangeSelector.js
src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/example.js
src/components/index.test.js
src/utils/timeline.js
yarn.lock

Resolves #64.
* Added an optional range selection feature to Time Travel component. Range selectors will be used in _Monitor_ part but not in _Explore_.
* Added an optional live/paused mode toggle to support the default auto-update mode in the dashboard charts.
* Reduced maximum timeline zoom level 2x.
* See if we settle at the current range intervals: `15min`, `30min`, `1h`, `3h`, `6h`, `24h`
* Consider alternative wording to _live_ / _paused_ states (and perhaps tweak the styling around it)
* Sticky switching to live mode should also work when pressing the right arrow on timeline
* Time Travel component is becoming too massive (> 800 lines atm). We should distribute its logic between various subcomponents (_RangeSelector_ already exists, we could make _TimestampInput_, …

Make Time Travel support ranges and live mode

---

docs/js/main.js
package.json
src/components/TimeTravel/TimeTravel.js
yarn.lock

Add normalize to the component viewer with a font-family workaround which we are using in `service-ui`.
Fixed some button sizes which appear different on OSX and Chrome (corrected by normalize.css).

Use normalize.css and fix button sizes

---

src/components/TimeTravel/TimeTravel.js
src/constants/timeline.js
src/utils/timeline.js

Resolves #75.
* Removed zoom limit that depended on the selected range, making zoom min-zoom a constant again.
* Introduced a minimum width for the rendered intervals in Time Travel timeline to make selected range always visible.

Remove min-zoom constraint for Time Travel ranges

---

src/components/TimeTravel/TimeTravel.js
src/constants/timeline.js
src/utils/timeline.js

Will fix https://github.com/weaveworks/service-ui/issues/1534 when updated in `service-ui` repo.
The problem was that we were iterating through years by moving by `moment.duration(1, 'year').asMilliseconds()`. However, that integer is ambiguous and was one day short for leap years like 2016.
In this PR the iteration is done like `timestamp.add(1, 'year')` which always works correctly. The same iteration is also done for all other times units (for consistency).

Iterate through Time Travel time periods correctly

---

src/constants/timeline.js

Addresses https://github.com/weaveworks/service-ui/issues/1533#issuecomment-348170084 as part of https://github.com/weaveworks/service-ui/issues/1533.
Looks good on my Chrome and Firefox!

Shave off two pixels from Timeline min-range width

---

package.json
src/components/TimeTravel/TimeTravel.js
yarn.lock

Should finally resolve https://github.com/weaveworks/service-ui/issues/1533.
* Use `react-resize-aware` to have DOM triggers for resizing of timeline, not just the global viewport level ones.
* The DOM triggers still didn't help for a particular case of < > panning buttons icons being loaded, so fix the width of those buttons to `20px`.

Made Time Travel Timeline size-aware

---

.npmignore

https://stackoverflow.com/a/5534865
> The pattern dir/ excludes a directory named dir and (implicitly) everything under it.
> With dir/, Git will never look at anything under dir, and thus will never apply any of the “un-exclude” patterns to anything under dir.
Currently the files inside the styles folder are not being included in the package.

Keep style files in npmignore

---

.npmignore

This is required by the service-ui dev server.
https://github.com/weaveworks/service-ui/blob/master/client/webpack.local.config.js#L6

Remove resolvers.js from npmignore

---

.npmignore

`resolvers.js` required by the service-ui dev server imports `src/resolvers/`
Tested using `npm pack`, installing locally for `service-ui` and running the dev server.

Keep resolver files in npmignore

---

src/components/TimeTravel/TimeTravel.js

Resolves #69.
* **Minor API change:** `onTimestampLabelClick` handler has been renamed to `onTimelineLabelClick`
* Added a new handler `onTimelinePanButtonClick` that is now distinguished from clicks on timeline timestamp labels
* Made forward timeline pan button sticky switch to live mode when moving to the current timestamp

Make forward timeline pan button able to switch to live mode

---

src/components/TimeTravel/Timeline.js

Fix the resize handling that was originally introduced in #81 and got wrongly rebased in #78.
Will probably resolve https://github.com/weaveworks/service-ui/issues/1304.

Fix Time Travel timeline resize handler

---

src/components/TimeTravel/_LiveModeToggle.js
src/components/TimeTravel/_RangeSelector.js

Addresses parts of #71.
* Vertically aligned _RangeSelector_ dropdown to currently selected element
* Got rid of relative font-size in RangeSelector component (used to cause problems before)
* Removed the Firefox _LiveModeToggle_ button outline
* Are we good with the current range intervals?
* Live/paused states
* Do we keep the text or just the icons?
* How exactly should the transition look like?

Small improvements to Time Travel UI

---

package.json

Fixes an issue where tests were running after installing this lib via `yarn install`.
cc @aaron7

Only run CI steps on publish

---

.babelrc
docs/js/routes.js
package.json
src/components/Dropdown/Dropdown.js
src/components/Dropdown/Dropdown.test.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Dropdown/example.js
src/components/Dropdown/index.js
src/components/index.js
yarn.lock

Fixes #66 
Adds a generic dropdown component:
One component to rule them all! Should be overridable and usable for both the instance selector and whatever other dropdowns we want.

Add Dropdown component

---

src/components/TimeTravel/TimeTravel.js

This is a prerequisite for https://github.com/weaveworks/service-ui/pull/1523 to work well with Back/Forward browser buttons as there would be cases where `showingLive` bool would be modified from the URL query params and would have to be applied to Time Travel state from the outside, through _props_.
This case also justifies the use of `showingLive` as a prop, so I removed the comment that references the question raised in https://github.com/weaveworks/ui-components/pull/68#discussion_r152771727.

Make Time Travel react to showingLive prop change

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Input/Input.js

- Reduce left-padding from 24px to 12px
- Introduce padding at top/bottom of items container to balance ws

Balance dropdown paddings

---

src/components/TimeTravel/TimeTravel.js

Prerequisite for bumping `ui-components` version in Scope which will then resolve https://github.com/weaveworks/service-ui/issues/1304.

Do not use onChangeLiveMode callback in Time Travel if live mode is not supported

---

src/components/Alert/Alert.js
src/components/Alert/example.js
src/theme/weave.js

There is a slight confusion about default/info currently (code uses
default but text mentions info).
In addition to success/warning/error types, it makes sense to have two
more where one is shallow and the other emphasized.
`default` is currently blending in with the background as it's light
gray. The one this PR adds (`info`) would be emphasized. I took the
already existing status color for the `info` type.

 Add `info` type for Alert component

---

src/components/Alert/example.js
src/components/Button/example.js
src/components/Dialog/example.js
src/components/Dropdown/example.js
src/components/Grid/example.js
src/components/Input/example.js
src/components/ListItem/example.js
src/components/MatchedText/example.js
src/components/Menu/example.js
src/components/Text/example.js
src/components/WeaveCloudLogo/example.js

This PR makes all the examples use `<Example />` to separate samples. It will allow us to properly introduce the JSX alongside the rendered output in #114.

Use semantic components to mark examples

---

src/components/Alert/Alert.js

`opacity:0` on clickable blocks prevents any clicks to go through if the
alert is used as an overlay.
This PR hides the closeIcon if the alert is invisible to not intefer
with anything behind it.

Hide close button when alert is invisible

---

src/components/PrometheusGraph/_DeploymentAnnotations.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Tooltip.js

Fixes https://github.com/weaveworks/service-ui/issues/743.
The timestamp format is uglier (less humanized), but at least it's consistent with how Time Travel control shows it. We should probably decide on a better cross-app time format, but that's a separate issue (cc @bia).

Show time in UTC format in PrometheusGraph tooltip

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/example.js

This also re-adds the padding in the wrapper as well as margins the
divider for balanced whitespace.

Add support for groups in dropdown

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_Chart.js
src/components/PrometheusGraph/_DeploymentAnnotations.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Legend.js
src/components/PrometheusGraph/_Tooltip.js

Resolves https://github.com/weaveworks/service-ui/issues/1433.
* Added graph legend multiselect support via <kbd>Ctrl</kbd> + click.
* Introduced `multiSeriesByKey` in `prepareMultiSeries` for more correct calculations (if the initial list of multi-series is not sorted, we couldn't rely on the order, so we need keys instead of indices).
* Fixed the warning for wrong `timestamp` format forwarded to `_Tooltip` subcomponent.
* Added `propTypes` to `_Chart` private subcomponent.

Add support for PrometheusGraph legend Ctrl+click multiselect

---

src/components/Dropdown/Dropdown.js

Resolves #138.
Also adds dummy `key` to the `<Divider />` to get rid of _missing key_ warnings.

Fix Dropdown items prop type

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_ErrorOverlay.js
src/components/PrometheusGraph/_LoadingOverlay.js
src/components/PrometheusGraph/example.js

Resolves #142.
Currently, graph errors in Service UI dashboards & notebooks are rendered prior to the _PrometheusGraph_ component, but it makes more sense to have that logic inside the component.
One issue this will also solve is not showing the (re)loader if the error message was displayed - now we show the loader overlay on top of the error overlay.

Display errors in PrometheusGraph component

---

src/components/PrometheusGraph/PrometheusGraph.js

Resolves #146.
* Added `seconds` metric unit type to support time units
* Changed `none` to `numeric` metric type for consistency with backend

Add time metric unit to PrometheusGraph

---

src/components/PrometheusGraph/_Legend.js

With very large legend text, the layout engine tries to cram as much text as
possible before giving up and ellipsising.
Instead of constraining the legend item to 45% of allocated width, we push down
max-width to the text itself so we have a limit there.

promgraph: Put max-width on legend text to avoid overflowing the page

---

src/components/Button/__snapshots__/Button.test.js.snap
src/theme/weave.js

Resolves #157.
* Weaveworks logo
* Timeline vertical focus bar
* Scope selectors pin (e.g. metric selector)
* Error alerts
* Prometheus Graph error alert
* Form errors
* Error messages
* Failures, errors
* Billing tooltip?
* Danger button from the theme
* Various error messages
* Instance trial expired
* Billing payment error
* Billing remove (button?)
* Notifications expandable error
* Landing h3 - probably service error
* Snackbar error
---
* Login Google button background
* PromQL dropdown

Collapse red colors

---

src/components/Button/__snapshots__/Button.test.js.snap
src/theme/weave.js

Shifting ![](https://placehold.it/15/00bcd4/000000?text=+) _turquoise_  a little darker to ![](https://placehold.it/15/037aa9/000000?text=+) _#037AA9_ because this colour passes WCAG AA both as a background with white text and as colored text on a ![](https://placehold.it/15/fafafc/000000?text=+) _whitesmoke_ background.
Completes #161.

Shifting turquoise to a darker AA compliant shade

---

package.json
webpack.config.js
yarn.lock

Adds a `yarn docs:analyze` job to show the makeup of our docs bundle. Related to https://github.com/weaveworks/ui-components/issues/180.

Add bundle analyzer

---

src/theme/weave.js

Update colors in Weave theme from red to blue, according to Google's
[brand guidelines](https://developers.google.com/identity/sign-in/web/build-button).

Update Google brand colors

---

src/components/DataTable/DataTable.js
src/components/DataTable/DataTable.test.js
src/components/DataTable/_Header.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap
src/components/DataTable/example.js
src/components/DataTable/index.js
src/components/index.js
src/utils/compose.js

Fixes #191 
Adds a sortable table component that can be used to show large data sets. Mimics the current behavior of the tables found in Weave Cloud.
Video: https://drive.google.com/file/d/1S-SD02ejNBObz9iwIg3Dgv4p6JEgE5mj/view
Key info:
* This component uses a [render-prop](https://reactjs.org/docs/render-props.html#using-props-other-than-render) pattern to encapsulate the sorting logic and pass down the sorted data to child components. The `children` argument that gets passed in should be a function.
* Custom sorting logic can be applied via the `sortOverrides` prop. The example and unit tests have reference implementations

Add DataTable component

---

src/components/TimeTravel/_TimestampInput.js

Previously, when editing the timestamp value, the input field value was
replaced as soon as a loosely parsable date was found. This made editing
the timestamp cumbersome.
With this PR, the date will only be checked for validity and
subsequently sent to its parent only if Enter is pressed or the input loses
focus.

Submit timestamp value only on enter or blur

---

docs/js/Root.js
docs/js/routes.js
package.json
webpack.config.js

Fixes #10 
Adds some uglification, adds in the correct env variable, and skips evaluation of `_` prefixed files when evaluating documentation.
Bundle size goes from ~17MB to 2.6MB.
Before:
```
Hash: f03c02e51c363b2712c4
Version: webpack 1.13.3
Time: 16719ms
Asset       Size  Chunks             Chunk Names
fontawesome-webfont.eot     166 kB          [emitted]  
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]  
fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]  
fontawesome-webfont.ttf     166 kB          [emitted]  
fontawesome-webfont.svg     444 kB          [emitted]  
a7942249ca925ef356c0f2b1dab17ef3.woff      29 kB          [emitted]  
favicon.ico    7.16 kB          [emitted]  
docs.js    16.9 MB       0  [emitted]  docs
index.html  201 bytes …
```

Reduce docs bundle size via uglify and NODE_ENV env variable

---

src/components/Dialog/Dialog.js

- Move z-index to wrapper where it has weight against other components
on page.
- Don't really need to use z-index internally, just use DOM order.
Fixes https://github.com/weaveworks/service-ui/issues/2277

Fix Dialog z-index issues / occasional text overlap.

---

src/components/PrometheusGraph/PrometheusGraph.js

Resolves https://github.com/weaveworks/service-ui/issues/2285 by reverting the order of series colors for line (non-stacked) graphs.

Reverse graph colors order for line graphs

---

.stylelintrc
docs/css/demo.scss
docs/js/main.js
src/components/PrometheusGraph/_HoverInfo.js
src/components/PrometheusGraph/_Tooltip.js
src/components/Text/Text.js
src/components/Text/__snapshots__/Text.test.js.snap
src/components/TimeTravel/_RangeSelector.js
src/components/TimeTravel/_TimestampInput.js
src/theme/fonts.js
src/theme/index.js
styleguide/Fonts.js

First step in resolving #212.
Resolves #216.
**Note:** Some _Roboto_ text in `PrometheusGraph` tooltips, as well as `TimeTravel` timestamp input box was changed to _monospace_, resulting in different looks, most notably:

Enforce theme font families

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_Chart.js
src/components/PrometheusGraph/_Legend.js
src/components/PrometheusGraph/example.js

Resolves #198.
* Modified the way series keys are chosen so that they will differ from series names only if they repeat multiple times in the legend. So, when we know they don't repeat, we can assume `seriesKey === seriesName`.
* Added `onChangeLegendSelection` to `PrometheusGraph` to notify the outside world of legend selection changes.
* Added `selectedLegendKeys` prop to `PrometheusGraph` that overrides the local state whenever it's changed (this pattern has already been repeated in a lot of our React components that communicate their internal state with the outside world and it seems to work fine).
* Added an example of two correlated graphs which demonstrates how we could have a _global_ legend state selection system.

PrometheusGraph legend items selection hook

---

docs/js/ComponentsPage.js
src/components/TabSelect/Tab.js
src/components/TabSelect/TabSelect.js
src/components/TabSelect/TabSelect.test.js
src/components/TabSelect/_TabButton.js
src/components/TabSelect/__snapshots__/TabSelect.test.js.snap
src/components/TabSelect/example.js
src/components/TabSelect/index.js
src/components/index.js

Closes #190 
Adds a TabSelect component, borrowing heavily from the current implementation in service-ui.
I am kind of ignoring my own advice about introspecting into `children`, but I looked at some similar third party components and it seems like it might be okay. At least the `propType` validation will throw an error if any type of unreadable component shows up as a child.
API looks like this:
```javascript
<TabSelect>
<Tab label="A" name="a">
Tab A
</Tab>
<Tab label="B" name="b">
Tab B
</Tab>
<Tab label="C" name="c">
Tab C
</Tab>
</TabSelect>
```
Renders:

Add TabSelect component

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/_TimelineDeployments.js
src/components/TimeTravel/_TimelineLabel.js
src/components/TimeTravel/_TimelinePeriodLabels.js
src/components/TimeTravel/example.js
src/constants/timeline.js

Add support for https://github.com/weaveworks/service-ui/issues/1856.
The next step is to send the pass through deployments info from all the relevant places in Service UI.
**Note:** Deployment annotations sometimes overlap with timestamp labels - @bia and I thought it's ok to ignore that issue for the moment and address it in https://github.com/weaveworks/ui-components/issues/226 instead.

Support primitive deployment annotations in TimeTravel timeline

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/example.js

Follow-up to #227, needed for knowing which time interval to query for deployments in https://github.com/weaveworks/service-ui/issues/1856.
See the `TimeTravel` component example for testing:

Add TimeTravel callback for visible range change

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/_TimelineDeployments.js
src/components/TimeTravel/_TimelineLoader.js
src/components/TimeTravel/_TimelineRange.js
src/components/TimeTravel/example.js

Resolves #229 by showing a semi-transparent blinking overlay over the _free_ timeline area as discussed with @bia.
* Moved away from function `.bind(this)` syntax in a couple of places
* Used `height: 100%` in a couple of places instead of passing the timeline height prop
* Simplified the way deployment annotations are rendered
* Always capping all timeline ranges to the visible chunk of the timeline
**Note:** Test this by panning around the second timeline in the example (the one with deployments).

Add blinking timeline loader

---

circle.yml

https://circleci.com/docs/1.0/yarn/
Was causing issues with snapshots being rendered slightly differently in CI to local because of differing versions of autoprefixer.
https://circleci.com/gh/weaveworks/ui-components/813

use yarn on circle for consistency with dev

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/example.js

Adds the prop `withComponent` to give the ability to replace the default
toggle view.
Closes #221

Allow customizing toggle view for Dropdown

---

src/components/PrometheusGraph/PrometheusGraph.js

when passing `selectedLegendKeys` props and then selecting another
legend, the legend will reset when the component re-renders.
this PR sets a flag when the user has manually selected a label not to
be overridden on re-render
Needed as part of https://github.com/weaveworks/service-ui/pull/2676

if user manually sets legend, use that over props

---

src/components/TabSelect/TabSelect.js
src/components/TabSelect/_TabButton.js
src/components/TabSelect/example.js

Currently uses `theme.colors.sand` which is the background used across the site. Unsure if there are needs for different backgrounds in which case we can make this configurable?
Fixes #251

add secondary styling for TabSelect

---

src/components/DataTable/DataTable.js
src/components/DataTable/DataTable.test.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap
src/components/DataTable/example.js

Allows for arbitrary elements to be used as headers, ie Buttons, Dropdowns, etc.

Add extraHeaders prop to DataTable

---

docs/js/Example.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/CircularProgress/CircularProgress.js
src/components/DataTable/DataTable.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap
src/components/Dialog/Dialog.js
src/components/LogoProgress/LogoProgress.js
src/components/Menu/Menu.js
src/components/Menu/MenuItem.js
src/components/PrometheusGraph/_Legend.js
src/components/TabSelect/TabSelect.js
src/components/TabSelect/_TabButton.js
src/components/TabSelect/__snapshots__/TabSelect.test.js.snap
src/components/TimeTravel/_LiveModeToggle.js
src/components/TimeTravel/_RangeSelector.js
src/components/TimeTravel/_TimelineLabel.js
src/components/TimeTravel/_TimelinePanButton.js
src/components/_TimestampTooltip/TimestampTooltip.js
src/theme/atoms.js
src/theme/box-shadows.js
src/theme/colors.js
styleguide/Colors.js

UI components part of #259.
After some tiny normalizations, the primary colors spectrum consists of the following colors (rough usage estimates in brackets):
---
New color system (dropped 4 colors from above):
The naming convention was inspired by [Material Design](https://material.io/design/color/the-color-system.html#) and the discussion in #218.
cc @bia @miklosp 
----
**Note**: I also added the default tooltip info on the colors preview page and relaxed the saturation sorting criterion a bit.

Collapse purple theme colors

---

src/components/TimeTravel/TimeTravel.js
src/components/TimeTravel/_Timeline.js
src/components/TimeTravel/example.js

Fixes https://github.com/weaveworks/service-ui/issues/2677.
The timeline was bouncing back because it would sometimes get rerendered due to the parent component state change caused by `onUpdateVisibleRange` callback. The rerendering would happen before the `onChangeTimestamp` callback would update the timestamp, so the old timestamp would still be passed (and taken for the new `focusedTimestamp`).
This was fixed by updating the `focusedTimestamp` from props only if `timestamp` prop really changes, i.e. `nextTimestamp !== this.props.timestamp`.
* Made `TimeTravel` component a `PureComponent` for additional shallow props comparison, just in case
* Switched the example initial timestamps to UTC format, for greater compatibility
* Some cosmetic code changes caused by `prettier`

Fix timeline dragging regression

---

src/theme/colors.js
styleguide/Colors.js

Now the only "uncategorized" colors are neutral colors so I renamed the category:

Remove 3 redundant theme colors

---

src/components/PrometheusGraph/PrometheusGraph.js

That override seems to be a blocker in resolving https://github.com/weaveworks/service-ui/issues/2698.
@guyfedwards As far as I could tell, this PR works in combination with https://github.com/weaveworks/service-ui/pull/2747, so perhaps there was no need for the override in the first place. Please test these two PRs in combination with proxying and let me know if something's not wokring as it should.

Remove selectedLegendOverride in PrometheusGraph

---

src/components/Code/Code.js
src/components/Code/Code.test.js
src/components/Code/__snapshots__/Code.test.js.snap
src/components/Code/example.js
src/components/Code/index.js
src/components/index.js

I have tried to simplify the API and usage to be more intuitive although for more complex styled/dynamic setups there is still some jsx wrangling required.
Couple of things to discuss:
- current implementation has the content scroll when it overflows. I think this is the sanest option, but visually will change across different OS/Browsers?
- Do we want to shrink the copy button so it occupies less of the code space?
fixes #244

add Code component for showing/copying snippets

---

src/components/Code/Code.js
src/components/Code/Code.test.js
src/components/Code/__snapshots__/Code.test.js.snap
src/components/Code/example.js

visual differentiation between single command split across multiple
lines and multiple commands to be run in sequence
fixes #278 
Have added three new examples for the multiCommand variations, not sure if they are really needed, would probably be fine with one additional example? @fbarl thoughts?

add multiCommand prop to Code

---

src/components/TabSelect/TabSelect.js
src/components/TabSelect/_TabButton.js
src/components/TabSelect/example.js

used for code snippets in k8s onboarding, used for more inline tabs within
other page content

add small option for TabSelect

---

src/components/DataTable/DataTable.js
src/components/DataTable/DataTable.test.js
src/components/DataTable/_Header.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap

Adds some more functionality to cover things like custom header elements and header widths.
Needed for https://github.com/weaveworks/service-ui/issues/2691

Add width and element fields to DataTable header

---

src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Input/Input.js
src/components/PrometheusGraph/_ErrorOverlay.js
src/components/Search/__snapshots__/Search.test.js.snap
src/theme/atoms.js
src/theme/colors.js

Resolves #268.
Affects:
* Danger button
* Error alert
* All error messages
cc @bia

Get rid of status.error color in favor of different shades of theme orange

---

src/components/Dropdown/Dropdown.js
src/components/GraphEdge/GraphEdge.js
src/components/ResourceDial/ResourceDial.js
src/components/ResourceDial/example.js

stops collision with ring and pushes label onto newline center text
in preparation for weaveworks/service-ui/issues/2807
-    fix lints after new config merged
*before*
*after*

make label less than full width

---

src/components/Dialog/Dialog.js

Current it has a large top margin. Use flexbox to center no matter what the window size is.

Center Dialog vertically with flexbox

---

src/components/Dialog/Dialog.js
src/components/Dialog/Dialog.test.js
src/components/Dialog/example.js

Brings the `Dialog` component closer to / easier to use for https://github.com/weaveworks/service-ui/issues/2813#issuecomment-405962739 (inviting team members to Weave Cloud).

Extend Dialog component props

---

src/components/Input/Input.js
src/components/Input/Input.test.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/Input/example.js
src/components/Search/__snapshots__/Search.test.js.snap

-  validation icon caused change of dimensions and alignment when appearing
next to the input. This commit moves the icon inside the inputa nd adds a
padding so the content doesn't go underneath the icon.
- add proptypes, add test, update examples input
fixes #315 
The change to `input` being `width: 100%` will have an impact on existing uses of `Input`. I could only find one instance in service-ui where the inputs were being used without width being explicitly set, in the cloudwatch instructions. I have addressed that in https://github.com/weaveworks/service-ui/pull/2932

move validation icon inside input

---

src/components/Input/Input.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/Search/__snapshots__/Search.test.js.snap

Only show the message if there is a message value *and* the field
is invalid.
Move the margin for spacing between input and message to the message
itself so the space is not there when the message is not.
related #324
Spacing before has message margin even though there is no message to show:

tweak rules around validation display

---

src/components/PrometheusGraph/PrometheusGraph.js

This enables the user to have sensible keys constructed for each series - e.g. no need to append the index at the end when we know all the legend labels would be unique.

Add an optional getSeriesKey param to PromGraph

---

src/components/Dialog/Dialog.js
src/components/Dialog/Dialog.test.js

Due to being hidden with css only, and still added to the DOM, any child
component is instantiated when the containing page is rendered.
If you have  a Dialog child with any heavy computation, or any at all
for that matter, you would be doing it even though the dialog may never
be opened.
This commit changes that by only rendering the children when the dialog is
active.
fixes #357

only render children when the dialog is active

---

src/components/TimestampTag/TimestampTag.js
src/components/TimestampTag/example.js

If timestamp is absolute and compact, only show the date.
FOr new events UI design we show the date if more than 7days ago. We currently
don't  use absolute timestamp anywhere so this is low impact.

add format for compact absolute timestamp

---

src/components/GraphNode/GraphNode.js
src/components/GraphNode/_GraphNodeStatic.js
src/components/GraphNode/example.js
src/components/GraphNode/tags/_TagCamera.js

Prerequisite for https://github.com/weaveworks/scope/issues/3316.
The camera tag can be added to any node by passing `tag="camera"` to the component.

Add camera tag to GraphNode component

---

src/components/Input/Input.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/Search/__snapshots__/Search.test.js.snap

Makes Input component look the same on Firefox as on Chrome.
In particular, this will address https://github.com/weaveworks/service-ui/issues/3291.

Fix styles of Input component on Firefox

---

src/components/PrometheusGraph/_AxesGrid.js

Depends on https://github.com/weaveworks/ui-components/pull/391, that needs to be merged first.
If the top value is a `step` away the show the maxValue on the axis
closes #392
**before**
**after** (includes changes from https://github.com/weaveworks/ui-components/pull/391)

Prom graph top value

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/example.js

very long lists go off the bottom of the screen and so their values
cannot be accesssed. This commit sets a max-height of 10 items, and
then scroll.

add max-height for dropdown panel

---

src/components/Input/Input.js
src/components/Input/Input.test.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/Search/Search.js
src/components/Search/__snapshots__/Search.test.js.snap

This commit stops adding <label> to the DOM, when there is no
label prop provided. It also removes the margin - used to add space
between the label and input - when there is no label prop provided.
Removed margin reset that was no longer needed on Search component

only render labal if there is a label

---

src/styles/_mixins.scss

My VS code linter was complaining - not only is it unused but also malformed :)

Remove unused fade-in-out mixin

---

src/components/Button/Button.js
src/theme/selectors-test.js
src/theme/selectors.js

Composable selectors for grabbing values from props and specifically
theme in styled components.
Changes this:
`background-color: ${props => props.theme.colors.orange};`
into
`background-color: ${color('orange')}`
After implementing this I discovered the `fromAtoms` util and generally the `Atoms`
concept. @fbarl could you give me a breakdown about the thought behind that?

[RFC] - add selectors for grabbing theme values

---

src/components/PrometheusGraph/PrometheusGraph.js
src/components/PrometheusGraph/_Chart.js

This commit changes PrometheusGraph to only calculate timeScale and valueScale
when there is new data, not every render.
This solves performance bottleneck when 2000+ datapoints and 16graphs on a
page at once.
Profile CPU usage during a release:
Before
After
Time spent in function on canary release page:

perf: only calculate time and value scales on new data

---

README.md
package.json
yarn.lock

[![asciicast](https://asciinema.org/a/Rrjv4eRINyD9jkqnnoYTcVFse.svg)](https://asciinema.org/a/Rrjv4eRINyD9jkqnnoYTcVFse)
This only changes the version/release stage, not the publishing stage. It adds a clear separation between cutting a release locally and publishing that release publically.
add husky for githooks and commitlint
husky enables githooks through code and commit lint will lint commit
messages based on the conventional-changelog specification.
This will allow us to have auto generated changelogs
Move the pushing of git tags to the `prepublish` stage, this means
that cutting a release is purely a local affair, then publishing
will push the tag into the public domain.
fixes #407

build(release): move to standard-version

---

src/components/Alert/Alert.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Input/__snapshots__/Input.test.js.snap
src/theme/index.js
src/theme/selectors.js
src/theme/spacings.js

Introduce standard spacing to the theme

---

src/components/Dropdown/Dropdown.js
src/components/Dropdown/example.js

- Some OS's don't show scrollbars so we chop the last item in half.
Fixes #428

feat(dropdown): adjusts max-height to show it can be scrolled

---

src/components/Alert/Alert.js
src/components/Alert/__snapshots__/Alert.test.js.snap
src/components/Button/Button.js
src/components/Code/Code.js
src/components/DataTable/DataTable.js
src/components/DataTable/__snapshots__/DataTable.test.js.snap
src/components/Dialog/Dialog.js
src/components/Dropdown/Dropdown.js
src/components/Dropdown/__snapshots__/Dropdown.test.js.snap
src/components/Input/Input.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/ListItem/ListItem.js
src/components/Menu/MenuItem.js
src/components/PrometheusGraph/PrometheusGraph.js
src/components/ResourceDial/ResourceDial.js
src/components/Search/__snapshots__/Search.test.js.snap
src/components/TabSelect/TabSelect.js
src/components/TabSelect/_TabButton.js
src/components/TabSelect/__snapshots__/TabSelect.test.js.snap
src/components/TimeTravel/TimeTravel.js
src/theme/spacings.js
src/utils/example.js

Continues work after #400 
Here I've corrected #425 to a `16px` base, a [more appropriate model](https://twitter.com/adamwathan/status/1063492067916009473) coming out of discussion with @foot : 
Pixel alignment tweaks for symbols and icons will be ignored by this system.
Still to be addressed : 
- Standardising line heights throughout components to match spacing
- Standardise width and height of components?
- Grid component
- In depth breakdown of TimeTravel component
- Scaling components like DotSpinner
I will create new issues for these accordingly.

Standardise component padding and margins

---

src/components/Button/Button.js
src/components/Button/__snapshots__/Button.test.js.snap

From discussion with @miklosp and @fbarl, the `90px` button was looking too wide with shorter labels such as `Send` and `OK`.
`80px` is `16px` x 5, which fits well with our spacing system.

fix: decrease button min-width

---

src/components/CircularProgress/CircularProgress.js
src/components/CircularProgress/example.js

Standardise CircularProgress sizes to theme spacing

---

package.json
yarn.lock

vulnerability found in webpack-dev-server, update to patch
Addresses vulnerability alert on github

chore: upgrade webpack-dev-server 3.1.11 for security patch

---

package.json
yarn.lock

fix: update lodash >4.17.11 to address security vulnerability modifying
`Object.prototype`
* nvd.nist.gov/vuln/detail/CVE-2018-16487
* hackerone.com/reports/380873

fix: cve-2018-16487

---

docs/css/demo.scss

Related to #460, some small modernisations to the look of the landing page of our demo page.

Demo page aesthetic improvements

---

src/components/Dropdown/Dropdown.js

The above UI bug can happen in a situation where the label passed in is an object since objects are truthy in javascript.  Ideally, Flow should catch this kind of problem but since it doesn't (from what I can tell the type gets lost as it goes through the `lodash/find` on line 200), a type check here will work for now.

workaround for dropdown item label title `[object Object]`

---

src/components/ResourceDial/ResourceDial.js

New design of ResourceDial component

---

src/components/GraphNode/shapes/_ShapeDottedCylinder.js
src/components/GraphNode/shapes/_ShapeDottedTriangle.js

Currently the shapes look rather fuzzy,
so you could say that I made them dashed, rather than dotted.
This is work towards #475

Refine dotted GraphNode shapes

---

src/components/Search/Search.js
src/components/Search/__snapshots__/Search.test.js.snap

In the context of some of the new work we are doing, search would look better with larger text.
before
after

Larger text in search component

---

.circleci/config.yml
package.json
yarn.lock

Upgrades project to support node versions 12+
fixes: https://github.com/weaveworks/ui-components/issues/489
By the way, the issue I had before was simply due to `node-sass` (the node bindings) needing to be updated.  The version that was targeted before was from before node 12 existed.  I'm happy it was that simple!

chore(package): upgrades project to support node 12 (`>=8`)

---

yarn.lock

Background: https://github.com/advisories/GHSA-g78m-2chm-r7qv

chore: update websocket-extensions to ^0.1.4

---

README.md

Also remove link to weave-users list, it's closed. Update Slack resources as well.

docs: point out CoC
